defaultSourceData: "file"           # for import of data
defaultSourceModel: "file"           # for import of models
# file types that are allowed for import from Pandora ("ckan")
ckanFileTypes:
  - "xls"
  - "xlsx"
  - "csv"
  - "odt"
  - "txt"
ckanModelTypes:
  - "zip"
  - "osteobior"
githubRepo: "osteobior"        # for import of models
mainFolder: "predefinedModels"  # for import of models
fileExtension: "osteobior"      # for download of models
rPackageName: "OsteoBioR"       # for download and import of models

# parameters for plot styles
# default format of graph and axis titles of intervalTimePlot for all models
defaultIntervalTimePlotTitle:
  text: ""
  fontType: "plain"
  color: "#000000"
  size: 24
  hide: false

defaultIntervalTimePlotText:
  fontType: "plain"
  color: "#000000"
  size: 18
  hide: false

# default point style for each model
defaultPointStyle:
  dataPoints:
    symbol: 19
    color: "#002350"
    colorBg: "#002350"
    size: 2
    alpha: 1
    lineWidthBg: 2
    hide: false

# default range of axis for all models
plotRange:
  min: 0
  max: 1
  fromData: true

# default line style for each model
defaultLineStyle:
  colorL: "#002350"
  colorU: "#002350"
  alphaL: 0.9
  alphaU: 0.1
