defaultSourceData: "file"           # for import of data
defaultSourceModel: "file"           # for import of models
fileExtension: "osteobior"      # for download of models
rPackageName: "OsteoBioR"       # for download and import of models
